---
version: "3"
services:
  db1:
    image: postgres:13
    volumes:
      - pgdata1:/var/lib/postgresql/data
      - ./primary-scripts.d:/docker-entrypoint-initdb.d/
    networks:
      - backend
    env_file: ./shared.env

  db2:
    image: postgres:13
    depends_on:
      - db1
    volumes:
      - pgdata2:/var/lib/postgresql/data
      - ./replica-scripts.d:/docker-entrypoint-initdb.d/
    networks:
      - backend
    env_file: ./shared.env
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./pg-admin-hosts.json:/pgadmin4/servers.json
    ports:
      - 8000:80
    networks:
      - backend
    env_file: ./shared.env


networks:
  backend:

volumes:
  pgdata1:
  pgdata2:
  pgadmin:
